#!/usr/bin/env python3
"""Build .sna snapshots into the Spectrum firmware.

  python3 tools/embed_snaps.py src/spectrum/spectrum_snap_data.c \
      "Some Game=~/snaps/game.sna"

Each argument is NAME=PATH. A 48K .sna is 27 bytes of registers followed
by 49152 bytes of RAM, so 49179 in all; nothing else is accepted here.

The generated file is gitignored. No snapshots are distributed with this
project: supply your own, and check that whoever owns them allows it.
"""
import os
import sys

SNA_SIZE = 27 + 49152


def main():
    if len(sys.argv) < 3:
        sys.exit(__doc__)
    dst = sys.argv[1]
    entries = []
    for arg in sys.argv[2:]:
        if "=" not in arg:
            sys.exit("expected NAME=PATH, got %r" % arg)
        name, path = arg.split("=", 1)
        data = open(os.path.expanduser(path), "rb").read()
        if len(data) != SNA_SIZE:
            sys.exit("%s: %d bytes, expected %d for a 48K .sna"
                     % (name, len(data), SNA_SIZE))
        entries.append((name.strip(), data, os.path.basename(path)))

    with open(dst, "w") as f:
        f.write("/* GENERATED by tools/embed_snaps.py - do not edit.\n"
                " *\n"
                " * %d ZX Spectrum snapshot(s). This file is in .gitignore on\n"
                " * purpose and must not be committed or published.\n */\n\n"
                % len(entries))
        for i, (name, data, src) in enumerate(entries):
            f.write("/* %s (%s) */\n" % (name, src))
            f.write("static const unsigned char snap_%d[%d] = {\n" % (i, len(data)))
            for off in range(0, len(data), 16):
                f.write("  " + ",".join("0x%02x" % b for b in data[off:off + 16]) + ",\n")
            f.write("};\n\n")
        f.write("const struct { const char *name; const unsigned char *sna; int size; }\n"
                "spectrum_snap_catalogue[] = {\n")
        for i, (name, data, _) in enumerate(entries):
            f.write('  { "%s", snap_%d, %d },\n' % (name.replace('"', ""), i, len(data)))
        f.write("};\n\nconst int spectrum_snap_count = %d;\n" % len(entries))

    print("wrote %s: %d snapshot(s), %d bytes"
          % (dst, len(entries), sum(len(d) for _, d, _ in entries)))


main()
