#!/usr/bin/env python3
"""Turn a binary ROM image into a C array the firmware can link in.

Used for the owner's own dumped MSX BIOS (Sharp/Epcom Hotbit HB-8000),
which is deliberately NOT committed to this repo: the .rom file and the
generated .c file are both in .gitignore. Everyone else building this
repo just gets the C-BIOS fallback that ships in src/cbios_data.c.

  python3 tools/embed_rom.py hotbi13p/hotbit13p.rom src/hotbit_bios_data.c

The emitted array is `const` so it lands in flash (.rodata), not RAM.
"""
import sys, os

def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    src, dst = sys.argv[1], sys.argv[2]
    data = open(src, "rb").read()
    if len(data) != 32768:
        sys.exit("expected a 32768-byte MSX1 main BIOS+BASIC image, got %d bytes" % len(data))

    lines = []
    for off in range(0, len(data), 16):
        chunk = data[off:off + 16]
        lines.append("  " + ",".join("0x%02x" % b for b in chunk) + ",")

    with open(dst, "w") as f:
        f.write("/* GENERATED by tools/embed_rom.py from %s - do not edit.\n"
                " *\n"
                " * Dumped MSX1 BIOS+BASIC, 32KB, owner's own ROM. This file is in\n"
                " * .gitignore on purpose and must not be committed or published.\n"
                " */\n" % os.path.basename(src))
        f.write("const unsigned char local_bios_rom[32768] = {\n")
        f.write("\n".join(lines))
        f.write("\n};\n")
    print("wrote %s (%d bytes of ROM)" % (dst, len(data)))

main()
