#!/usr/bin/env python3
"""Build .tap tape images into the Spectrum firmware.

  python3 tools/embed_tapes.py src/spectrum/spectrum_tape_data.c roms/spectrum

Every .tap in the directory is taken, named after the file.

Prefer snapshots: tools/tapes_to_snaps.sh converts a tape into a .sna that
starts instantly, and a tape only earns its place in the firmware when the
conversion fails. Keeping both wastes flash on the same game twice.

The generated file is gitignored. Nothing is distributed with this project;
these came from World of Spectrum, from publishers recorded there as having
given permission.
"""
import os
import sys


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    dst, srcdir = sys.argv[1], sys.argv[2]
    names = sorted(n for n in os.listdir(srcdir) if n.lower().endswith(".tap"))
    if not names:
        sys.exit("no .tap files in " + srcdir)

    total = 0
    with open(dst, "w") as f:
        f.write("/* GENERATED by tools/embed_tapes.py - do not edit.\n"
                " *\n"
                " * %d ZX Spectrum tape images. This file is in .gitignore on\n"
                " * purpose and must not be committed or published.\n */\n\n" % len(names))
        for i, n in enumerate(names):
            data = open(os.path.join(srcdir, n), "rb").read()
            total += len(data)
            f.write("/* %s, %d bytes */\n" % (n, len(data)))
            f.write("static const unsigned char tape_%d[%d] = {\n" % (i, len(data)))
            for off in range(0, len(data), 16):
                f.write("  " + ",".join("0x%02x" % b for b in data[off:off + 16]) + ",\n")
            f.write("};\n\n")

        f.write("const struct { const char *name; const unsigned char *tap; int size; }\n"
                "spectrum_tape_catalogue[] = {\n")
        for i, n in enumerate(names):
            title = os.path.splitext(n)[0].replace('"', "")
            size = os.path.getsize(os.path.join(srcdir, n))
            f.write('  { "%s", tape_%d, %d },\n' % (title, i, size))
        f.write("};\n\nconst int spectrum_tape_count_n = %d;\n" % len(names))

    print("wrote %s: %d tapes, %d bytes (%dkB)" % (dst, len(names), total, total // 1024))


main()
