#!/usr/bin/env python3
"""Turn a binary ROM image into a C array the firmware can link in.

Used for the owner's own dumped MSX BIOS (Sharp/Epcom Hotbit HB-8000),
which is deliberately NOT committed to this repo: the .rom file and the
generated .c file are both in .gitignore. Everyone else building this
repo just gets the C-BIOS fallback that ships in src/cbios_data.c.

  python3 tools/embed_rom.py hotbi13p/hotbit13p.rom src/hotbit_bios_data.c
  python3 tools/embed_rom.py game.rom src/local_cart_data.c local_cart_rom

The emitted array is `const` so it lands in flash (.rodata), not RAM -
which is the whole point: this board has no room to hold a 32kB image in
RAM alongside the emulated machine.
"""
import sys, os

def main():
    if len(sys.argv) not in (3, 4):
        sys.exit(__doc__)
    src, dst = sys.argv[1], sys.argv[2]
    symbol = sys.argv[3] if len(sys.argv) == 4 else "local_bios_rom"
    data = open(src, "rb").read()
    if symbol == "local_bios_rom" and len(data) != 32768:
        sys.exit("expected a 32768-byte MSX1 main BIOS+BASIC image, got %d bytes" % len(data))
    if len(data) % 8192:
        sys.exit("expected a whole number of 8kB pages, got %d bytes" % len(data))

    lines = []
    for off in range(0, len(data), 16):
        chunk = data[off:off + 16]
        lines.append("  " + ",".join("0x%02x" % b for b in chunk) + ",")

    with open(dst, "w") as f:
        f.write("/* GENERATED by tools/embed_rom.py from %s - do not edit.\n"
                " *\n"
                " * Somebody else's ROM image, %d bytes. This file is in .gitignore\n"
                " * on purpose and must not be committed or published.\n"
                " */\n" % (os.path.basename(src), len(data)))
        f.write("const unsigned char %s[%d] = {\n" % (symbol, len(data)))
        f.write("\n".join(lines))
        f.write("\n};\n")
    print("wrote %s (%d bytes of ROM)" % (dst, len(data)))

main()
