#!/usr/bin/env python3
"""Build a catalogue of cartridge images into the firmware.

This board has no room to hold a cartridge in RAM - a 32kB image does not
fit next to 64kB of emulated RAM - so images live in flash and are run
from there. That also means they can be selected at boot without a card
in the slot, which is the point.

  python3 tools/embed_roms.py src/msx/local_cart_data.c \
      "Castle Excellent=~/roms/castle.rom" \
      "Nemesis=~/roms/nemesis.rom"

Each argument is NAME=PATH. Names are what the boot menu shows. Sizes must
be a power of two in 8kB pages: anything else would have to be mirrored,
and mirroring means writing into the image, which cannot be done in flash.

The generated file is gitignored. No ROM images belong in this repository.
"""
import os
import sys


def emit_array(f, symbol, data):
    f.write("static const unsigned char %s[%d] = {\n" % (symbol, len(data)))
    for off in range(0, len(data), 16):
        f.write("  " + ",".join("0x%02x" % b for b in data[off:off + 16]) + ",\n")
    f.write("};\n\n")


def main():
    if len(sys.argv) < 3:
        sys.exit(__doc__)
    dst = sys.argv[1]
    entries = []

    for arg in sys.argv[2:]:
        if "=" not in arg:
            sys.exit("expected NAME=PATH, got %r" % arg)
        name, path = arg.split("=", 1)
        data = open(os.path.expanduser(path), "rb").read()

        pages = len(data) >> 13
        if len(data) % 8192 or pages == 0 or (pages & (pages - 1)):
            sys.exit("%s: %d bytes is not a power of two number of 8kB pages"
                     % (name, len(data)))
        entries.append((name.strip(), data, os.path.basename(path)))

    total = sum(len(d) for _, d, _ in entries)
    with open(dst, "w") as f:
        f.write("/* GENERATED by tools/embed_roms.py - do not edit.\n"
                " *\n"
                " * Other people's cartridge images, %d of them, %d bytes in all.\n"
                " * This file is in .gitignore on purpose and must not be\n"
                " * committed or published.\n */\n\n" % (len(entries), total))
        for i, (name, data, src) in enumerate(entries):
            f.write("/* %s (%s), %dkB */\n" % (name, src, len(data) // 1024))
            emit_array(f, "cart_%d" % i, data)

        f.write("const struct { const char *name; const unsigned char *rom; int size; }\n"
                "msx_cart_catalogue[] = {\n")
        for i, (name, data, _) in enumerate(entries):
            f.write('  { "%s", cart_%d, %d },\n' % (name.replace('"', ""), i, len(data)))
        f.write("};\n\n")
        f.write("const int msx_cart_count = %d;\n" % len(entries))

    print("wrote %s: %d cartridges, %d bytes (%dkB)"
          % (dst, len(entries), total, total // 1024))


main()
