#!/usr/bin/env python3
"""Regenerate EMULib/MIDIFreq.h, which upstream fMSX ships but this
vendored copy was missing.

It is a plain lookup table: index = frequency/3 in Hz, value = the MIDI
note and pitch-wheel position that comes closest to that frequency. Only
Sound.c's MIDI logging path reads it (MIDINote/MIDIWheel), which this
build does not use, but Sound.c does not compile without it.

  python3 tools/gen_midifreq.py > lib/fmsx_core/EMULib/MIDIFreq.h
"""
import math

print("/* GENERATED by tools/gen_midifreq.py - MIDI note + pitch wheel per")
print(" * frequency step, for EMULib/Sound.c's MIDI output path. */")
for j in range(4096):
    hz = j * 3.0
    if hz < 8.0:
        note, wheel = 0, 8192
    else:
        v = 69.0 + 12.0 * math.log(hz / 440.0, 2.0)
        note = int(math.floor(v))
        frac = v - note
        if note < 0:
            note, frac = 0, 0.0
        if note > 127:
            note, frac = 127, 0.0
        wheel = int(8192 + frac * 4096.0)
        wheel = max(0, min(16383, wheel))
    print("{%d,%d}," % (note, wheel))
