"""PlatformIO pre-build hook: use the owner's own dumped BIOS if it's here.

src/hotbit_bios_data.c is generated by tools/embed_rom.py from a local ROM
dump and is gitignored, so it exists only on the owner's machine. When it
does, define HAVE_LOCAL_BIOS so MSX.c embeds that BIOS (which boots
MSX-BASIC) instead of C-BIOS (which is cartridge-only). A clone without
the ROM still builds and runs, just with C-BIOS.
"""
import os

Import("env")  # noqa: F821  (injected by PlatformIO)

bios_c = os.path.join(env.subst("$PROJECT_SRC_DIR"), "hotbit_bios_data.c")
if os.path.isfile(bios_c):
    env.Append(CPPDEFINES=["HAVE_LOCAL_BIOS"])
    print("local BIOS: src/hotbit_bios_data.c found, embedding it (MSX-BASIC available)")
else:
    print("local BIOS: not present, falling back to C-BIOS (cartridge-only, no MSX-BASIC)")
